sudo: required

services:
    - docker

branches:
    only:
    - master

before_install:
    - docker pull schmidtw/webpa.builder.centos6:latest
    - docker run -it -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -d --name build schmidtw/webpa.builder.centos6 bash
    - docker exec build git clone https://github.com/Comcast/caduceus.git

script:
    - docker exec build bash -c "pushd caduceus; ./build_rpm.sh; popd"

after_success:
    - docker cp build:/root/rpmbuild/RPMS/x86_64 .
    - docker cp build:/versionno.txt .
    - BINARY_NAME=`ls x86_64/`
    - TRAVIS_TAG=`cat versionno.txt`

deploy:
  provider: releases
  prerelease: true
  api_key: $AUTH_TOKEN_BUILD
  file: x86_64/$BINARY_NAME
  skip_cleanup: true

